# Generated by Django 3.0.6 on 2020-05-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20200526_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
