# Generated by Django 3.0.6 on 2020-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20200527_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/sample.jpg', upload_to='media/'),
        ),
    ]
