# Generated by Django 3.0.6 on 2020-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20200528_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='/sample.jpg', upload_to='media/'),
        ),
    ]
